# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
# on:
  # # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Python setup
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      # Ros Setup
      - uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic

      # Pip setup
      - uses: BSFishy/pip-action@v1
        with:
          requirements: python_requirements.txt

      # Setup Julia environment
      - name: Setup Julia environment
        # You may pin to the exact commit or the version.
        # uses: julia-actions/setup-julia@e18229af6aa41b9a9b569bc4a9ce1d456ce9acc3
        uses: julia-actions/setup-julia@v1.5.1
      
      # Buld Julia pkg
      - name: Build Julia pkg
        uses: julia-actions/julia-buildpkg@latest
      
      # Test Julia pkg
      - name: Test Julia pkg
        uses: julia-actions/julia-runtest@latest
